# Advanced Numpy

✅ What is Advanced Indexing?

Advanced indexing means:

👉 Indexing an array using lists, arrays, boolean masks, or multiple indices to select specific elements.

It is more powerful than normal slicing.

✅ Types of Advanced Indexing
✅ 1. Integer Array Indexing

You use a list/array of indices to pick specific elements.

In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
idx = [0, 2, 4]

print(arr[idx])

[10 30 50]


In [2]:
arr[[1,4]]

array([20, 50])

✅ 2. Integer Indexing on 2D Array

In [3]:
arr = np.array([
    [10, 11, 12],
    [20, 21, 22],
    [30, 31, 32]
])

rows = [0, 2]
cols = [1, 2]

print(arr[rows, cols])

[11 32]


Meaning:

(row 0, col 1) → 11

(row 2, col 2) → 32

👉 Picks pair-wise elements.

✅ 3. Boolean Indexing (VERY IMPORTANT)

Boolean indexing means:

👉 Selecting elements from an array using True/False conditions.

If condition is True → element is selected
If condition is False → element is skipped

In [4]:
arr = np.array([5, 12, 18, 7, 3])
print(arr[arr > 10]) #Meaning → Pick values greater than 10.


[12 18]


✅ Boolean Indexing in 2D

In [5]:
arr = np.array([
    [10, 50],
    [30, 5]
])

print(arr[arr > 20])


[50 30]


In [6]:
a=np.random.randint(0,100,24).reshape(6,4)
a

array([[65, 30, 11, 37],
       [69, 59, 50, 67],
       [72, 73, 75, 64],
       [83, 64, 77, 26],
       [48, 31, 64,  0],
       [56, 91, 48, 95]])

In [7]:
a>50 #it gives boolean array 
#find all the number greater than 50 

array([[ True, False, False, False],
       [ True,  True, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True, False],
       [False, False,  True, False],
       [ True,  True, False,  True]])

In [8]:
a[a>50]

array([65, 69, 59, 67, 72, 73, 75, 64, 83, 64, 77, 64, 56, 91, 95])

In [9]:
a[(a>50) & (a%2==0)] # & this and is use for boolean indexing 
#it show the value which is greater then 50 and it is divisible by 2 also.

array([72, 64, 64, 64, 56])

In [10]:
a[a > 90] = 0
print(a)

[[65 30 11 37]
 [69 59 50 67]
 [72 73 75 64]
 [83 64 77 26]
 [48 31 64  0]
 [56  0 48  0]]


In [11]:
names = np.array(["Ram", "Amit", "Ram", "Sita"])
marks = np.array([85, 90, 75, 95])
print(marks[names == "Ram"])

[85 75]


✅ Why do we create arrays like this?

Because now each index matches:

Index	Name	Marks
0	Ram	85
1	Amit	90
2	Ram	75
3	Sita	95

That means:

names[0] → "Ram"

marks[0] → 85

✅ They belong together.

Step 1: Create a boolean mask

names == "Ram"

Output:

[ True False  True False ]

This means:

index 0 → Ram ✅

index 1 → Amit ❌

index 2 → Ram ✅

index 3 → Sita ❌

✅ Step 2: Use mask to filter marks

marks[names == "Ram"]

NumPy will select only the places where mask is True:

✅ For index 0 → 85
✅ For index 2 → 75

Final Output:

[85 75]

✅ How it works in simple language

Check which names are "Ram".

Wherever it is True, pick the marks from the marks array.

Return only those marks.

In [12]:
a[(a>50)&(a%7==0)]

array([77, 56])

In [13]:
a[~(a%7==0)] #~this sign is not 
#this shows the number not divisible by 7 

array([65, 30, 11, 37, 69, 59, 50, 67, 72, 73, 75, 64, 83, 64, 26, 48, 31,
       64, 48])

✅ 4. Fancy Indexing

Fancy indexing means:

👉 Using lists, arrays, or multiple indices to pick specific rows or columns from a NumPy array.

It is more powerful than normal indexing or slicing.

In [14]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(arr[[0, 2]])

[[10 20 30]
 [70 80 90]]


In [15]:
a=np.arange(0,12).reshape(3,4)

In [16]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
a=a.reshape(4,3)

In [18]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [19]:
a[[0,2,3]]

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [20]:
a2=np.arange(24).reshape(6,4)#rows columns
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [21]:
a2[[0,2,5]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [20, 21, 22, 23]])

In [22]:
a2[:,[0,2,3]] #it shows all rows and columns 0 , 2 and 3


array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [23]:
a2[[2,3,5],:]#it shows all columns and all the 2,3 5 rows

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [24]:
a2[[2,3,4,5]]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [25]:
a2[[-1,-2]]

array([[20, 21, 22, 23],
       [16, 17, 18, 19]])

In [26]:
print(a2[[1, 1, 1]])#will print row one 3 times

[[4 5 6 7]
 [4 5 6 7]
 [4 5 6 7]]


✅ Select specific columns:

In [27]:
print(arr[:, [0, 2]])

[[10 30]
 [40 60]
 [70 90]]


✅ 5. Mix of Boolean + Integer Indexing

In [28]:
arr = np.array([
    [2, 5, 8],
    [3, 9, 1],
    [4, 6, 7]
])

row_mask = [True, False, True]

print(arr[row_mask, 1])

[5 6]


✅ What is Broadcasting? (Easy Explanation)

Broadcasting = NumPy automatically expands smaller arrays so they can match bigger arrays during operations.

👉 It allows you to do math between arrays of different shapes.

✅ You do NOT need loops

NumPy does it automatically.

✅ Very simple rule
✅ Broadcasting works when:

Dimensions are equal, OR

One of them is 1 (NumPy stretches it), OR

One array has missing dimensions (NumPy adds automatically)

In [29]:
arr=np.array([20,30,40,50])
print(arr+5) # 5 is add with all the elements in arr 
#Why?
#5 becomes [5, 5, 5,5] automatically (broadcasting).

[25 35 45 55]


In [30]:
arr_2=np.array([[1],[2],[3],[4]])
print(arr+arr_2)


[[21 31 41 51]
 [22 32 42 52]
 [23 33 43 53]
 [24 34 44 54]]


In [31]:
a = np.array([1, 2, 3])
b = np.array([[10],
              [20],
              [30]])
print(a + b)


[[11 12 13]
 [21 22 23]
 [31 32 33]]


✅ How Broadcasting works here

a shape → (3,)
b shape → (3,1)

NumPy expands them:

a → [1 2 3]

      ↓ ↓ ↓ expands down

      ↓ ↓ ↓
b → [[10 10 10]

     [20 20 20]

     [30 30 30]]

Then adds corresponding values.

✅ Rule of Broadcasting

✅ Broadcasting works only if:

Arrays have same number of dimensions (NumPy adds 1s if needed)

In every dimension:
sizes must match OR one of them must be 1

❌ If a dimension is different and not 1, broadcasting fails.

✅ Allowed when:

numbers are equal

OR one of them is 1

In [32]:
arr=np.arange(1,10).reshape(3,3)
row=np.array([10,20,30])
print(arr+row)

[[11 22 33]
 [14 25 36]
 [17 28 39]]


Why?

Row → [10,20,30] broadcasts to all 3 rows.

In [33]:
col=np.array([[10],
              [20],
              [30]]) #Column broadcasts to each column.
print(row+col)

[[20 30 40]
 [30 40 50]
 [40 50 60]]


❌ Example 1 — Broadcasting Not Possible

Arrays:

A = np.array([1, 2, 3])        # Shape → (3,)

B = np.array([10, 20])         # Shape → (2,)

✅ Check broadcasting rules

Compare shapes from the end:

A : (3,)
B : (2,)

3 ≠ 2

No dimension is 1
👉 Broadcasting fails

❌ Example 2 — 2D & 2D mismatch
Arrays:

A = np.array([[1,2,3],

              [4,5,6]])       # Shape → (2, 3)

B = np.array([[10,20],

              [30,40]])       # Shape → (2, 2)

Compare shapes (from the end):
A : (2, 3)
B : (2, 2)

Check each dimension:

A	B	Valid?

3	2	❌ No match, none is 1

2	2	✅ match

Because 3 ≠ 2 → no stretching possible.

In [34]:
A = np.zeros((3, 4, 5))     # Shape → (3, 4, 5)
B = np.ones((4, 1))         # Shape → (4, 1)
print(A+B)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [35]:
a=np.arange(12).reshape(4,3) #4 rows and 3 columns 
b=np.arange(3)

print(a)
print(b)
print("a+b=")
print(a+b)
""" 
b will become after brocasting 
[[0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]]
 
 shape of a was (4,3)
 shape of b was (,3)
 so it make shape of b as (1,3)
 then it make it to (4,3) 
"""

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
a+b=
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


' \nb will become after brocasting \n[[0 1 2]\n [0 1 2]\n [0 1 2]\n [0 1 2]]\n\n shape of a was (4,3)\n shape of b was (,3)\n so it make shape of b as (1,3)\n then it make it to (4,3) \n'

In [36]:
a=np.arange(12).reshape(3,4) #4 rows and 3 columns 
b=np.arange(3)

print(a)
print(b)
""" 
it can not be add now becuse the shape of a is (3,4) and b is (,3)
so if we make b shape as (1,3) than we convert it to (3,3) by making it 3 times  
so it's not possible to make it as (3,4)
"""

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2]


" \nit can not be add now becuse the shape of a is (3,4) and b is (,3)\nso if we make b shape as (1,3) than we convert it to (3,3) by making it 3 times  \nso it's not possible to make it as (3,4)\n"

In [37]:
a=np.arange(3).reshape(1,3)
b=np.arange(3).reshape(3,1)

print(a)
print(b)
print("a+b=")
print(a+b)
""" 
now the shape of a is (1,3) and shape of b is (3,1) to broadcasting this we need to convert shape of a by making 
it 3 time (3,3) then b broadcast the shape of b from (3,1) to (3,3) 
so the addtion is posible 
"""

[[0 1 2]]
[[0]
 [1]
 [2]]
a+b=
[[0 1 2]
 [1 2 3]
 [2 3 4]]


' \nnow the shape of a is (1,3) and shape of b is (3,1) to broadcasting this we need to convert shape of a by making \nit 3 time (3,3) then b broadcast the shape of b from (3,1) to (3,3) \nso the addtion is posible \n'

## Working With Mathematical Formulas

In [38]:
# 1/1+e**-x
def sigmoid_function(array):
    return (1/(1+np.exp(-(array))))

a=np.arange(100)
sigmoid_function(a)

array([0.5       , 0.73105858, 0.88079708, 0.95257413, 0.98201379,
       0.99330715, 0.99752738, 0.99908895, 0.99966465, 0.99987661,
       0.9999546 , 0.9999833 , 0.99999386, 0.99999774, 0.99999917,
       0.99999969, 0.99999989, 0.99999996, 0.99999998, 0.99999999,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.     

In [39]:
actual=np.random.randint(1,50,25)
predicted=np.random.randint(1,50,25)
print(actual)
print(predicted)

[44 41 19 13 27 49 22 47 37 42 14 29 24  9  3 24 16 19 42 38 46 41 44 37
 39]
[ 4 44 34 46 44 10 10 41  5 44 41 48 22  3 47  1 44 34 31 43 48 24  3 16
 43]


In [40]:
def mse(actual,predicted):
    return np.mean((actual-predicted)**2)

print(mse(actual,predicted))

524.88


### Find missing values

In [41]:
import numpy as np

arr = np.array([10, 20, np.nan, 40])
result = np.isnan(arr)

print(result)

[False False  True False]


In [42]:
np.sum(np.isnan(arr)) #Count missing values

1

In [43]:
np.any(np.isnan(arr)) #Check if any missing value exists it returns True 

True

In [44]:
np.where(np.isnan(arr)) #Find index of missing value

(array([2], dtype=int64),)

In [45]:
arr2 = np.array([[1, 2], [np.nan, 4]])

np.isnan(arr2) #2D Array Example

array([[False, False],
       [ True, False]])

In [46]:
arr3=np.array([[[1,2],[3,4]],[[5,np.nan],[7,8]]])
np.isnan(arr3) #3D Array Example

array([[[False, False],
        [False, False]],

       [[False,  True],
        [False, False]]])